on:
  pull_request:
    branches:
      - main

name: Validate code

jobs:
  validate:
    name: Typescript + ESLint
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16.x

      - name: Installing dependencies
        run: npm i

      - name: Compiling Typescript
        run: npm run tsc

      - name: Running ESLint
        run: npm run lint-workflow
